export = {
  contents= {
    {
      creator= "initiator",
      description= {
        mux= true,
        encryption= {
          },
        feedback= {
          },
        sources= {
          },
        sourceGroups= {
          },
        media= "audio",
        headerExtensions= {
          {
            id= "1",
            senders= "both",
            uri= "urn:ietf:params:rtp-hdrext:ssrc-audio-level",
            },
          {
            id= "3",
            senders= "both",
            uri= "http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time",
            },
          },
        payloads= {
          {
            feedback= {
              },
            name= "opus",
            clockrate= "48000",
            id= "111",
            channels= "2",
            parameters= {
              {
                key= "minptime",
                value= "10",
                },
              },
            },
          {
            feedback= {
              },
            name= "PCMU",
            clockrate= "8000",
            id= "0",
            channels= "",
            },
          {
            feedback= {
              },
            name= PCMA,
            clockrate= "8000",
            id= "8",
            channels= "",
            },
          {
            feedback= {
              },
            name= "ISAC",
            clockrate= "16000",
            id= "103",
            channels= "",
            },
          {
            feedback= {
              },
            name= "ISAC",
            clockrate= "32000",
            id= "104",
            channels= "",
            },
          },
        descType= "rtp",
        },
      name= "audio",
      senders= "both",
      transport= {
        ufrag= "1v8rh1945k1u2j",
        transType= "iceUdp",
        pwd= "5vih74ib4bt6rftogeeo28usmc",
        fingerprints= {
          {
            value= "CA:71:53:79:00:5A:AF:15:42:18:26:AB:AC:23:CC:BC:8F:E0:CE:38",
            setup= "actpass",
            hash= "sha-1",
            },
          },
        candidates= {
          {
            type= "host",
            protocol= "udp",
            id= "0",
            ip= "192.168.6.36",
            component= "1",
            port= "10003",
            foundation= "1",
            generation= "0",
            priority= "2130706431",
            network= "1",
            },
          {
            type= "host",
            protocol= "udp",
            id= "1",
            ip= "10.208.225.101",
            component= "1",
            port= "10003",
            foundation= "",
            generation= "0",
            priority= "2130706431",
            network= "1",
            },
          {
            type= "host",
            protocol= "udp",
            id= "2",
            ip= "2001:4800:7818:101:be76:4eff:fe05:69a4",
            component= "1",
            port= "10003",
            foundation= "3",
            generation= "0",
            priority= "2113939711",
            network= "1",
            },
          {
            type= "host",
            protocol= "udp",
            id= "3",
            ip= "23.253.245.117",
            component= "1",
            port= "10003",
            foundation= "4",
            generation= "0",
            priority= "2113932031",
            network= "1",
            },
          {
            type= "srflx",
            protocol= "ssltcp",
            id= "4",
            ip= "2001:4800:7818:101:be76:4eff:fe05:69a4",
            component= "1",
            port= "443",
            foundation= "11",
            generation= "0",
            network= "1",
            priority= "1677732095",
            relPort= "4443",
            relAddr= "2001:4800:7818:101:be76:4eff:fe05:69a4",
            },
          {
            type= "srflx",
            protocol= "ssltcp",
            id= "5",
            ip= "192.168.6.36",
            component= "1",
            port= "443",
            foundation= "9",
            generation= "0",
            network= "1",
            priority= "1677724415",
            relPort= "4443",
            relAddr= "192.168.6.36",
            },
          {
            type= "srflx",
            protocol= "ssltcp",
            id= "6",
            ip= "10.208.225.101",
            component= "1",
            port= "443",
            foundation= "10",
            generation= "0",
            network= "1",
            priority= "1677724415",
            relPort= "4443",
            relAddr= "10.208.225.101",
            },
          {
            type= "srflx",
            protocol= "ssltcp",
            id= "7",
            ip= "23.253.245.117",
            component= "1",
            port= "443",
            foundation= "12",
            generation= "0",
            network= "1",
            priority= "1677724415",
            relPort= "4443",
            relAddr= "23.253.245.117",
            },
          },
        },
      },
    {
      creator= "initiator",
      description= {
        mux= true,
        encryption= {
          },
        feedback= {
          },
        sources= {
          },
        sourceGroups= {
          },
        media= "video",
        headerExtensions= {
          {
            id= "2",
            senders= "both",
            uri= "urn:ietf:params:rtp-hdrext:toffset",
            },
          {
            id= 3,
            senders= "both",
            uri= "http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time",
            },
          },
        payloads= {
        {
            feedback= {
              {
                id= "100",
                type= "ccm",
                parameters= {
                  },
                subtype= "fir",
                },
              {
                id= "100",
                type= "nack",
                parameters= {
                  },
                subtype= "",
                },
              {
                id= "100",
                type= "goog-remb",
                parameters= {
                  },
                subtype= "",
                },
              },
            name= "VP8",
            clockrate= "90000",
            id= "100",
            channels= "",
            },
          {
            feedback= {
              },
            name= "red",
            clockrate= "90000",
            id= "116",
            channels= "",
            },
          },
        descType= "rtp",
        },
      name= "video",
      senders= "both",
      transport= {
        ufrag= "1v8rh1945k1u2j",
        transType= "iceUdp",
        pwd= "5vih74ib4bt6rftogeeo28usmc",
        fingerprints= {
          {
            value= "CA:71:53:79:00:5A:AF:15:42:18:26:AB:AC:23:CC:BC:8F:E0:CE:38",
            setup= "actpass",
            hash= "sha-1",
            },
          },
        candidates= {
          {
            type= "host",
            protocol= "udp",
            id= "8",
            ip= "192.168.6.36",
            component= "1",
            port= "10003",
            foundation= "1",
            generation= "0",
            priority= "2130706431",
            network= "1",
            },
          {
            type= "host",
            protocol= "udp",
            id= "9",
            ip= "10.208.225.101",
            component= "1",
            port= "10003",
            foundation= "2",
            generation= "0",
            priority= "2130706431",
            network= "1",
            },
          {
            type= "host",
            protocol= "udp",
            id= "10",
            ip= "2001:4800:7818:101:be76:4eff:fe05:69a4",
            component= "1",
            port= "10003",
            foundation= "3",
            generation= "0",
            priority= "2113939711",
            network= "1",
            },
          {
            type= "host",
            protocol= "udp",
            id= "11",
            ip= "23.253.245.117",
            component= "1",
            port= "10003",
            foundation= "4",
            generation= "0",
            priority= "2113932031",
            network= "1",
            },
          {
            type= "srflx",
            protocol= "ssltcp",
            id= "12",
            ip= "2001:4800:7818:101:be76:4eff:fe05:69a4",
            component= "1",
            port= "443",
            foundation= "11",
            generation= "0",
            network= "1",
            priority= "1677732095",
            relPort= "4443",
            relAddr= "2001:4800:7818:101:be76:4eff:fe05:69a4",
            },
          {
            type= "srflx",
            protocol= "ssltcp",
            id= "13",
            ip= "192.168.6.36",
            component= "1",
            port= "443",
            foundation= "9",
            generation= "0",
            network= "1",
            priority= "1677724415",
            relPort= "4443",
            relAddr= "192.168.6.36",
            },
          {
            type= "srflx",
            protocol= "ssltcp",
            id= "14",
            ip= "10.208.225.101",
            component= "1",
            port= "443",
            foundation= "10",
            generation= "0",
            network= "1",
            priority= "1677724415",
            relPort= "4443",
            relAddr= "10.208.225.101",
            },
          {
            type= "srflx",
            protocol= "ssltcp",
            id= "15",
            ip= "23.253.245.117",
            component= "1",
            port= "443",
            foundation= "12",
            generation= "0",
            network= "1",
            priority= "1677724415",
            relPort= "4443",
            relAddr= "23.253.245.117",
            },
          },
        },
      },
    {
      name= "data",
      description= {
        descType= "datachannel",
        },
      creator= "initiator",
      transport= {
        ufrag= "1v8rh1945k1u2j",
        transType= "iceUdp",
        pwd= "5vih74ib4bt6rftogeeo28usmc",
        sctp= {
          {
            number= "5000",
            protocol= "webrtc-datachannel",
            streams= "1024",
            },
          },
        fingerprints= {
          {
            value= "CA:71:53:79:00:5A:AF:15:42:18:26:AB:AC:23:CC:BC:8F:E0:CE:38",
            setup= "actpass",
            hash= "sha-1",
            },
          },
        candidates= {
          {
            type= "host",
            protocol= "udp",
            id= "16",
            ip= "192.168.6.36",
            component= "1",
            port= "10003",
            foundation= "1",
            generation= "0",
            priority= "2130706431",
            network= "1",
            },
          {
            type= "host",
            protocol= "udp",
            id= "17",
            ip= "10.208.225.101",
            component= "1",
            port= "10003",
            foundation= "2",
            generation= "0",
            priority= "2130706431",
            network= "1",
            },
          {
            type= "host",
            protocol= "udp",
            id= "18",
            ip= "2001:4800:7818:101:be76:4eff:fe05:69a4",
            component= "1",
            port= "10003",
            foundation= "3",
            generation= "0",
            priority= "2113939711",
            network= "1",
            },
          {
            type= "host",
            protocol= "udp",
            id= "19",
            ip= "23.253.245.117",
            component= "1",
            port= "10003",
            foundation= "4",
            generation= "0",
            priority= "2113932031",
            network= "1",
            },
          {
            type= "srflx",
            protocol= "ssltcp",
            id= "20",
            ip= "2001:4800:7818:101:be76:4eff:fe05:69a4",
            component= "1",
            port= "443",
            foundation= "11",
            generation= "0",
            network= "1",
            priority= "1677732095",
            relPort= "4443",
            relAddr= "2001:4800:7818:101:be76:4eff:fe05:69a4",
            },
          {
            type= "srflx",
            protocol= "ssltcp",
            id= "21",
            ip= "192.168.6.36",
            component= "1",
            port= "443",
            foundation= "9",
            generation= "0",
            network= "1",
            priority= "1677724415",
            relPort= "4443",
            relAddr= "192.168.6.36",
            },
          {
            type= "srflx",
            protocol= "ssltcp",
            id= "22",
            ip= "10.208.225.101",
            component= "1",
            port= "443",
            foundation= "10",
            generation= "0",
            network= "1",
            priority= "1677724415",
            relPort= "4443",
            relAddr= "10.208.225.101",
            },
          {
            type= "srflx",
            protocol= "ssltcp",
            id= "23",
            ip= "23.253.245.117",
            component= "1",
            port= "443",
            foundation= "12",
            generation= "0",
            network= "1",
            priority= "1677724415",
            relPort= "4443",
            relAddr= "23.253.245.117",
            },
          },
        },
      },
    },
  groups= {
    {
      contents= {
        "audio",
        "video",
        "data",
        },
      semantics= "BUNDLE",
      },
    },
  }